name-template: "web-$RESOLVED_VERSION"
tag-template: "web-$RESOLVED_VERSION"
categories:	
  - title: "機能"	
    labels: ["enhancement"]	
  - title: "バグ修正"	
    labels: ["bug"]	
  - title: "その他"	
    labels: ["refactor", "test"]	
exclude-labels:
  - 'release'
template: |	
  ## 変更内容	
  $CHANGES 