on:
  # release ブランチへのプルリクが close されたタイミングで動く
  pull_request:
    # @see https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    branches:
      - release
    types: [closed]

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    # マージ以外の理由で close された場合にも動いてしまうので、マージされた場合だけに限定します
    if: github.event.pull_request.merged == true
    steps:
      - name: Create New Version
        id: create-new-version
        run: |
          # timezone を JST にする
          # カレンダーバージョニング
          # @see https://calver.org/
          _new_version=`TZ="Asia/Tokyo" date '+%y.%m%d.%H%M'`
          # 後続の処理で new_version で参照出来ます
          echo ::set-output name=new_version::${_new_version}
      - name: Create Release
        id: create_release
        # steps.create-new-version で生成された new_version で release 作成します
        # @see https://github.com/actions/create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          # v20.0701.1939 みたいなイメージです
          # vYY.mmdd.HHMM
          tag_name: v${{ steps.create-new-version.outputs.new_version }}
          release_name: v${{ steps.create-new-version.outputs.new_version }}
          # draft で留めておくので手動で released してください
          draft: true
          prerelease: false