
name: Deploy Hoge
on:
  release:
    types:
      - released
      - deleted

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'hoge')
    steps:
      - name: get latest tag name
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git tag -l "fuga-*" | sort -r | head -n1)
          echo "::set-output name=latest_tag::$LATEST_TAG"
      - name: test
        run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ steps.get-latest-tag.outputs.latest_tag }}