
name: Debug
on:
  push:
    paths:
      - ".gthub/workflows/test.yml"
      - "README.md"
    branches:
      - main

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run 
        run: cat README.md

