
name: Deploy Hoge
on:
  release:
    types:
      - released
      - deleted

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.release.tag_name }}